### ISSUE TITLE
Unable to get this to work

### ISSUE THREAD

**Issue by aaronrosenbergNSMG** [isaac-galvan/nagios-teams-notify#1]
I'm trying to get this to work. I believe i have everything configured correctly, but i'm just not able to send a notification. Is there anyway to simulate or build in logging?

**Comment by mrysn** [comment]
I've got it successfully working in a production environment. Do you know what errors you're seeing? Have you installed python3 and dependencies imported in the python script?

**Comment by aaronrosenbergNSMG** [comment]
I figured it out, it was a noob mistake. I didn’t make the script executable.


Aaron Rosenberg

IT Manager

1900 St. James Place, Ste. 300

Houston, TX 77056

(P) 832.308.2717; (m) 832-413-2931
www.nsmg.com<http://www.nsmg.com/>
